name: Go

on:
  push:
    branches: [ "main" ]
    tags-ignore:
      - "v*"          # prevent infinite loops when pushing tags
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04 ## Only works on ubuntu 22.04 

    permissions:
      contents: write   # required for tags + GitHub releases
      packages: write   # required for GHCR push

    steps:
      # -------------------------------
      # Checkout
      # -------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # REQUIRED for tag calculation
          lfs: true

      - name: Install packages
        run: |
          ls -la
          sudo apt update -y
          sudo apt install wget curl libguestfs-tools -y

      - name: WGET
        run: wget https://cloud-images.ubuntu.com/questing/current/questing-server-cloudimg-amd64.img

      - name:  Resize
        run: |
          qemu-img create -f qcow2 questing-expanded.img 8G
          sudo virt-resize --expand /dev/sda1 questing-server-cloudimg-amd64.img questing-expanded.img

      - name:  Extend cloud image
        run: |
          sudo virt-customize -a questing-expanded.img --commands-from-file 'run-command.virt'
          ls -la

      - name:  Compress cloud image
        run: |
          sudo virt-sparsify --compress questing-expanded.img questing-desktop-cloudimg-amd64.img
          ls -la

      # -------------------------------
      # Versioning & Release (main only)
      # -------------------------------
      - name: Bump version and create tag
        if: github.event_name == 'push'
        id: tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main

      - name: Stamp release image filename
        if: github.event_name == 'push' && steps.tag.outputs.new_tag != ''
        run: |
          mv questing-desktop-cloudimg-amd64.img questing-desktop-cloudimg-amd64-${{ steps.tag.outputs.new_tag }}.img
          ls -la

      - name: Create GitHub release
        if: github.event_name == 'push' && steps.tag.outputs.new_tag != ''
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag.outputs.new_tag }}
          name: Release ${{ steps.tag.outputs.new_tag }}
          body: ${{ steps.tag.outputs.changelog }}
          artifacts: questing-desktop-cloudimg-amd64-${{ steps.tag.outputs.new_tag }}.img
